services:
  redis:
    restart: always
    image: redis:alpine
    container_name: redis_container
    volumes:
      - redis_data:/data/cache
    ports:
      - 6379:6379
    networks:
      - redis

  mongo:
    restart: always
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo

  backend:
    container_name: backend_container
    restart: always
    build:
      context: ./backend
    depends_on:
      - redis
      - mongo
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    networks:
      - redis
      - mongo
      - web

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
    ports:
      - 4173:4173
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - web

  nginx:
    container_name: nginx_container
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - web

volumes:
  mongo_data:
  redis_data:

networks:
  redis:
  mongo:
  web: